### ISSUE TITLE
[Upstream]: LND 0.15.3

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/service-pipeline#28]
- [ ] https://github.com/Start9Labs/lnd-wrapper/issues/63
- [ ] https://github.com/Start9Labs/lnd-wrapper/issues/59
- [ ] https://github.com/Start9Labs/lnd-wrapper/issues/54
- [ ] https://github.com/Start9Labs/lnd-wrapper/issues/41
- [ ] https://github.com/Start9Labs/lnd-wrapper/issues/36 [IN PROGRESS]

**Comment by kn0wmad** [comment]
Dupe of #29?

**Comment by kn0wmad** [comment]
I noticed that.  I'm confused why there are 2 updates?

**Comment by chrisguida** [comment]
Because it's impossible to get all of the above done in time for the 0.15.0 release

**Comment by chrisguida** [comment]
Assigning to @islandbitcoin

**Comment by chrisguida** [comment]
I'll finish the js properties conversion, doesn't need to go with 0.15.1
