### ISSUE TITLE
[Upstream]: LND 0.15.0

### ISSUE THREAD

**Issue by islandbitcoin** [Start9Labs/service-pipeline#29]
- [x] https://github.com/Start9Labs/lnd-wrapper/issues/62
- [x] https://github.com/Start9Labs/lnd-wrapper/issues/64
- [x] #30 
- [x] #58
- [x] #57 
- [x] https://github.com/Start9Labs/s9-services/issues/50
- [ ] https://github.com/Start9Labs/lnd-wrapper/issues/47
- [x] https://github.com/Start9Labs/s9-services/issues/48
- [x] https://github.com/Start9Labs/s9-services/issues/55
- [ ] https://github.com/Start9Labs/s9-services/issues/56
- [ ] https://github.com/Start9Labs/s9-services/issues/59
- [ ] Regression test on v0.3.1.1

**Comment by chrisguida** [comment]
Excellent issue

**Comment by chrisguida** [comment]
At what point are you checking these off? The child releases have actually not gone out yet

**Comment by chrisguida** [comment]
This has a bug with the `cipher_seed_mnemonic` when starting a new node. Putting back into "in progress" until this is fixed.
