### ISSUE TITLE
[Upstream]: Photoview v2.3.13

### ISSUE THREAD

**Issue by islandbitcoin** [Start9Labs/service-pipeline#35]
- [ ] https://github.com/Start9Labs/embassyos-photoview-wrapper/issues/11
- [ ] https://github.com/Start9Labs/embassyos-photoview-wrapper/issues/10
- [ ] https://github.com/Start9Labs/embassyos-photoview-wrapper/issues/9
- [ ] https://github.com/Start9Labs/embassyos-photoview-wrapper/issues/8
- [ ] https://github.com/Start9Labs/photoview-wrapper/issues/12

**Comment by chrisguida** [comment]
@MattDHill This is up for grabs if you want it

**Comment by chrisguida** [comment]
Waiting for the user with this issue to test @BitcoinMechanic @islandbitcoin

**Comment by BitcoinMechanic** [comment]
Waiting for her to get back to me

**Comment by elvece** [comment]
This is in the "Done" column but are all checklist items completed?
