### ISSUE TITLE
[Service Request]: Prosody

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/service-pipeline#37]
An implementation would need to be selected.  My suggestion is Prosody

**Comment by MattDHill** [comment]
Approved pending @dr-bonez confirmation of Prosody suggestion.

**Comment by dr-bonez** [comment]
I think prosody is probably the right approach

**Comment by chrisguida** [comment]
Needs rewrite before publishing to alpha

**Comment by chrisguida** [comment]
Needs rewrite before publishing to alpha according to @MattDHill
