### ISSUE TITLE
[Initial]: Ghost v5.13.2

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/service-pipeline#40]

**Comment by MattDHill** [comment]
Approved

**Comment by chrisguida** [comment]
@k0gen how's this going?

**Comment by k0gen** [comment]
It is going well - started using it on my production Embassy [HERE](http://gur7ib3qijvmlpjw43dmxxwgvazhswucha4dgz6xrrcsnta5pjjab7qd.onion)

**Comment by chrisguida** [comment]
🔥

**Comment by chrisguida** [comment]
Waiting for @MattDHill to test and decide whether the issues are blocking releasse

**Comment by elvece** [comment]
This is in the "Done" column but the issue is not closed, is it completed?
