### ISSUE TITLE
[Service Request]: Jellyfin

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/service-pipeline#45]
Alternative: https://github.com/xbmc/xbmc  (XMBC is former name)

Alternative: Plex (https://github.com/plexinc/pms-docker) 

A media server is a powerful tool for a home server, better suited to the Pro device than the raspi, but if this is all you want, the raspi will do the trick

**Comment by MattDHill** [comment]
Kodi and/or Plex approved

**Comment by kn0wmad** [comment]
@dr-bonez does this have architectural approval?
