### ISSUE TITLE
[Upstream]: LNDg v1.2.1

### ISSUE THREAD

**Issue by islandbitcoin** [Start9Labs/service-pipeline#48]
- [x] https://github.com/Start9Labs/lndg-wrapper/issues/8
- [x] https://github.com/Start9Labs/lndg-wrapper/issues/7
- [x] https://github.com/Start9Labs/lndg-wrapper/issues/5

**Comment by chrisguida** [comment]
released to prod https://github.com/Start9Labs/lndg-wrapper/releases/tag/v1.2.1
