### ISSUE TITLE
[Upstream]: Thunderhub v0.13.14

### ISSUE THREAD

**Issue by islandbitcoin** [Start9Labs/service-pipeline#50]
- [x] https://github.com/Start9Labs/thunderhub-wrapper/issues/21
- [x] https://github.com/Start9Labs/thunderhub-wrapper/issues/15
- [x] https://github.com/Start9Labs/thunderhub-wrapper/issues/20

**Comment by chrisguida** [comment]
released to prod https://github.com/Start9Labs/thunderhub-wrapper/releases/tag/v0.13.14
