### ISSUE TITLE
[Upstream]: Mastodon v3.5.3

### ISSUE THREAD

**Issue by islandbitcoin** [Start9Labs/service-pipeline#52]
- [ ] https://github.com/Start9Labs/mastodon-wrapper/issues/21
- [ ] https://github.com/Start9Labs/mastodon-wrapper/issues/20
- [ ] https://github.com/Start9Labs/mastodon-wrapper/issues/19
- [ ] https://github.com/Start9Labs/mastodon-wrapper/issues/13
- [ ] https://github.com/Start9Labs/mastodon-wrapper/issues/11
- [ ] https://github.com/Start9Labs/mastodon-wrapper/issues/2

**Comment by chrisguida** [comment]
@k0gen how's this going?
