### ISSUE TITLE
[Upstream]: File Browser v2.22.4

### ISSUE THREAD

**Issue by islandbitcoin** [Start9Labs/service-pipeline#53]
- [ ] https://github.com/Start9Labs/filebrowser-wrapper/issues/21
- [ ] https://github.com/Start9Labs/filebrowser-wrapper/issues/26
- [ ] https://github.com/Start9Labs/filebrowser-wrapper/issues/12

**Comment by chrisguida** [comment]
@Blu-J how's this going?

**Comment by Blu-J** [comment]
Web dav is not coming for a while, if ever. Dependent on new features from the os.
filebrowser-wrapper#12, don't I have to go into filebrowser itself, why didn't we create a feature there?

Could do the update to the filebrowser is the only one here doable?

**Comment by chrisguida** [comment]
Ok thanks. Regarding filebrowser-wrapper#12, that's a question for @MattDHill

**Comment by chrisguida** [comment]
@Blu-J Yeah, whatever you can do in the next release should go in this ticket. Anything you're leaving for later should go in a new ticket, with the version number incremented.

**Comment by MattDHill** [comment]
> Ok thanks. Regarding filebrowser-wrapper#12, that's a question for @MattDHill

I'm not sure if File Browser offers alternative means of authenticating. If not, perhaps auth timeout is configurable. If not this would have to be changed in FB itself, either by us or FB team Let me know.

**Comment by elvece** [comment]
This is in the "Done" column but are all checklist items completed?
