### ISSUE TITLE
[Maintenance]: Synapse v1.63.1

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/service-pipeline#54]
### What kind of service is this?

Messaging

### What does this service do?

```shell
Matrix implementation
```

### How does this service work?

```shell
n/a
```

### What alternative services exist?

```shell
Other matrix implementations (Conduit, Dendrite), XMPP, IRC, etc
```

### How does this align with our Mission?

- [X] Freedom Tech
- [X] Data Privacy
- [ ] Bitcoin/Lightning
- [ ] Open Source Dev

### How complex is this service?

Hard

### How popular is this service?

High Demand

### Upstream Repo of Proposed Service

https://github.com/Start9Labs/synapse-wrapper

**Comment by kn0wmad** [comment]
WIP already by k0gen

**Comment by k0gen** [comment]
```
Successfully uploaded synapse.s9pk
Successfully indexed synapse@1.63.1
```
On Alpha and Beta
