### ISSUE TITLE
[Upstream]: BalanceofSatoshis v12.16.2

### ISSUE THREAD

**Issue by islandbitcoin** [Start9Labs/service-pipeline#55]
- [ ] https://github.com/Start9Labs/balanceofsatoshis-wrapper/issues/2
- [ ] https://github.com/Start9Labs/balanceofsatoshis-wrapper/issues/1

**Comment by chrisguida** [comment]
released https://github.com/Start9Labs/balanceofsatoshis-wrapper/releases/tag/v12.16.2
