### ISSUE TITLE
[Upstream]: Lightning Jet v1.4.4

### ISSUE THREAD

**Issue by islandbitcoin** [Start9Labs/service-pipeline#57]

**Comment by cryptodread** [comment]
- [ ] https://github.com/Start9Labs/lightning-jet-wrapper/issues/3
- [ ] https://github.com/Start9Labs/lightning-jet-wrapper/issues/2
- [ ] https://github.com/Start9Labs/lightning-jet-wrapper/issues/1

**Comment by chrisguida** [comment]
released to prod https://github.com/Start9Labs/lightning-jet-wrapper/releases/tag/v1.5.0
