### ISSUE TITLE
[Upstream]: RTL v0.13.1

### ISSUE THREAD

**Issue by islandbitcoin** [Start9Labs/service-pipeline#58]
- [x] https://github.com/Start9Labs/ride-the-lightning-wrapper/issues/20
- [x] https://github.com/Start9Labs/ride-the-lightning-wrapper/issues/19

TODO:
- [ ] https://github.com/Start9Labs/ride-the-lightning-wrapper/issues/15
- [ ] js migrations

**Comment by cryptodread** [comment]
- [ ] https://github.com/Start9Labs/ride-the-lightning-wrapper/issues/20

**Comment by chrisguida** [comment]
Moved https://github.com/Start9Labs/ride-the-lightning-wrapper/issues/19 up from v0.12.3.4 to v0.12.3.3

**Comment by chrisguida** [comment]
Updated upstream to 0.13

**Comment by chrisguida** [comment]
Waiting for upstream 0.13.1 with bugfix for creating private channels from liquidity ads page

**Comment by chrisguida** [comment]
Released https://github.com/Start9Labs/ride-the-lightning-wrapper/releases/tag/v0.13.1
