### ISSUE TITLE
[Upstream]: Sphinx Relay v2.2.9

### ISSUE THREAD

**Issue by islandbitcoin** [Start9Labs/service-pipeline#59]

**Comment by chrisguida** [comment]
<img width="1006" alt="Screen Shot 2022-07-28 at 3 50 33 PM" src="https://user-images.githubusercontent.com/7445670/181635115-b4c67e3f-74d0-43ef-b37c-6958a3d833f2.png">

https://github.com/stakwork/sphinx-relay/wiki/Home-node-FAQ

**Comment by chrisguida** [comment]
Released https://github.com/Start9Labs/sphinx-relay-wrapper/releases/tag/v2.2.9
