### ISSUE TITLE
[Compatibility Bump]: BTCPS v1.4.7.4

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/service-pipeline#62]

**Comment by chrisguida** [comment]
- [ ] https://github.com/Start9Labs/btcpayserver-wrapper/pull/29

**Comment by elvece** [comment]
- [ ] https://github.com/Start9Labs/btcpayserver-wrapper/pull/30

**Comment by elvece** [comment]
Closing in favor of https://github.com/orgs/Start9Labs/projects/85/views/1?filterQuery=btc

**Comment by chrisguida** [comment]
In the future, feel free to simply rename the service release issue instead of making an entirely new one.

**Comment by chrisguida** [comment]
Released
