### ISSUE TITLE
[Maintenance]: Spark v0.3.1.4

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/service-pipeline#63]

**Comment by kn0wmad** [comment]
@chrisguida Is this for compatibility with CLN v0.12?  @gStart9 we can knock this out in very short order

**Comment by chrisguida** [comment]
George is already working on it

**Comment by gStart9** [comment]
Tested and uploaded latest build to Alpha.

Latest PR https://github.com/Start9Labs/spark-wallet-wrapper/pull/18

**Comment by gStart9** [comment]
Tested & published to Beta last night.

**Comment by kn0wmad** [comment]
Looking good to me, please announce to beta testers in appropriate Matrix channels

**Comment by chrisguida** [comment]
released to prod https://github.com/Start9Labs/spark-wallet-wrapper/releases/tag/v0.3.1.4
