### ISSUE TITLE
[Service Request]: LndHub

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/service-pipeline#7]
### What kind of service is this?

Lightning

### What does this service do?

```shell
This is used by Bluewallet (possibly others?) for connecting to LND.

It also divides up your LND wallet into "accounts" which are given their own credentials, so this is potentially a way to "uncle jim" an LND node.

It's on alpha already, but it doesn't seem to work that well over Tor. More testing is needed.
```

### How does this service work?

```shell
You run it alongside LND and then connect to it in Bluewallet.
```

### What alternative services exist?

```shell
Lnbits? I think does about the same thing
```

### How does this align with our Mission?

- [X] Freedom Tech
- [X] Data Privacy
- [X] Bitcoin/Lightning
- [ ] Open Source Dev

### How complex is this service?

Easy

### How popular is this service?

Low Demand

### Upstream Repo of Proposed Service

https://github.com/BlueWallet/LndHub

### Wrapper Implementation

https://github.com/chrisguida/lndhub-wrapper

**Comment by kn0wmad** [comment]
I'm not sure this fits the "Dev" category

**Comment by chrisguida** [comment]
@kn0wmad What would you say *does* fit that category?

**Comment by chrisguida** [comment]
@cryptodread what were you imagining for "open source dev"? Do any of our current sources fit this category?

**Comment by cryptodread** [comment]
first - all of the categories are imagined out of my head, so feel free to suggest changes. 
I imagined the dev category would be things like code-server, gitea, or other self-hosted IDE tools

**Comment by MattDHill** [comment]
Green lit

**Comment by kn0wmad** [comment]
This can probably be closed since it is available in LNBits
